[package]
name = "menubar"
version = "0.0.1"
authors = ["Mads Marquart <mads@marquart.dk>"]
edition = "2018"

[dependencies]
winit = "0.25"
raw-window-handle = "0.3"
env_logger = "0.8"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
core-foundation = "0.9"
objc = { git = "https://github.com/madsmtm/rust-objc", branch = "smart-references" }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "wincon"] }
