[package]
name = "menubar"
version = "0.0.1"
authors = ["Mads Marquart <mads@marquart.dk>"]
edition = "2018"

[target.'cfg(target_os = "macos")'.dependencies]
objc = { git = "https://github.com/madsmtm/rust-objc", rev = "d067bbd8d6da8a0ff56b3819dd11dcd10c15148a" }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "wincon"] }

[dev-dependencies]
winit = "0.25"
raw-window-handle = "0.3"
env_logger = "0.8"
